#!/bin/sh

# IOS - Projekt 1. - skript (wrapper) wedi
# Autor - Jakub Frejlach (xfrejl00)
# Datum - 27.3.2018

export POSIXLY_CORRECT=yes

if [ -z "$WEDI_RC" ]; then
  echo "CHYBA:Promenna WEDI_RC je prazdna." >&2
  exit 1
fi

if [ ! -d "$(dirname "$WEDI_RC")" ]; then
  mkdir -p "$(dirname "$WEDI_RC")"
fi

if [ ! -f "$WEDI_RC" ]; then
  touch "$WEDI_RC"
fi

if [ "$(uname)" = "Linux" ]; then
  SEDFNC="sed"
else
  SEDFNC="gsed"
fi

FILE_CHECK=$(cut -f2 -d':' "$WEDI_RC" | sort | uniq)
for LOG in $FILE_CHECK; do
  if [ -f "$LOG" ]; then
    continue
  else
    "$SEDFNC" -i 's|'.*"$LOG".*'||g' "$WEDI_RC"
    "$SEDFNC" -i '/^[[:space:]]*$/d' "$WEDI_RC"
  fi
done

command -v realpath >/dev/null
if [ "$?" -eq 127 ]; then
  echo "CHYBA:Realpath neni dostupna." >&2
  exit 1
fi

edit="$EDITOR"
if [ -z "$EDITOR" ]; then
    edit="$VISUAL"
    if [ -z "$VISUAL" ]; then
      edit="vi"
    fi
fi

if [ $# -eq "1" ] && [ -f "$1" ]; then
  $edit "$(realpath "$1")"
  CODE="$?"
  echo "${1##*/}:$(realpath "$1"):$(date +%Y-%m-%d)" >> "$WEDI_RC"
  exit "$CODE"
fi

if [ $# -eq "1" ] && [ -d "$1" ]; then
  DIRECTORY=$(realpath "$1")
  FILE=$(grep "$DIRECTORY/[^/]*:" "$WEDI_RC" | cut -d':' -f1 | tail -n1)
  if [ -z "$FILE" ]; then
    echo "CHYBA:V adresari nebyl jeste editovany zadny soubor." >&2
    exit 1
  else
    $edit "$(realpath "$FILE")"
    CODE="$?"
    echo "$FILE:$(realpath "$FILE"):$(date +%Y-%m-%d)" >> "$WEDI_RC"
    exit "$CODE"
  fi
fi

if [ $# -eq "0" ]; then
  DIRECTORY=$(realpath .)
  FILE=$(grep "$DIRECTORY/[^/]*:" "$WEDI_RC" | cut -d':' -f1 | tail -n1)
  if [ -z "$FILE" ]; then
    echo "CHYBA:V adresari nebyl jeste editovany zadny soubor." >&2
    exit
  else
    $edit "$(realpath "$FILE")"
    CODE="$?"
    echo "$FILE:$(realpath "$FILE"):$(date +%Y-%m-%d)" >> "$WEDI_RC"
    exit "$CODE"
  fi
fi

if [ "$1" = "-m" ]; then
  if [ -d "$2" ] && [ $# -eq "2" ]; then
    DIRECTORY=$(realpath "$2")
    FILE=$(grep "$DIRECTORY/[^/]*:" "$WEDI_RC" | cut -d':' -f1 | sort | uniq -c | sort | tail -n1 | tr -s ' ' | cut -d ' ' -f 3)
    if [ -z "$FILE" ]; then
      echo "CHYBA:V adresari nebyl jeste editovany zadny soubor." >&2
      exit 1
    else
      $edit "$(realpath "$FILE")"
      CODE="$?"
      echo "$FILE:$(realpath "$FILE"):$(date +%Y-%m-%d)" >> "$WEDI_RC"
      exit "$CODE"
    fi
  elif [ $# -eq "1" ]; then
    DIRECTORY=$(realpath .)
    FILE=$(grep "$DIRECTORY/[^/]*:" "$WEDI_RC" | cut -d':' -f1 | sort | uniq -c | sort | tail -n1 | tr -s ' ' | cut -d ' ' -f 3)
    if [ -z "$FILE" ]; then
      echo "CHYBA:V adresari nebyl jeste editovany zadny soubor." >&2
      exit
    else
      $edit "$(realpath "$FILE")"
      CODE="$?"
      echo "$FILE:$(realpath "$FILE"):$(date +%Y-%m-%d)" >> "$WEDI_RC"
      exit "$CODE"
    fi
  else
    echo "CHYBA: Zadany adresar neexistuje" >&2
    exit 1
  fi


elif [ "$1" = "-l" ]; then
  if [ -d "$2" ] && [ $# -eq "2" ]; then
    DIRECTORY=$(realpath "$2")
    FILE=$(grep "$DIRECTORY/[^/]*:" "$WEDI_RC" | cut -d':' -f1 | sort | uniq)
    if [ -z "$FILE" ]; then
      exit 0
    fi
    echo "$FILE"
    exit 0
  elif [ $# -eq "1" ]; then
    DIRECTORY=$(realpath .)
    FILE=$(grep "$DIRECTORY/[^/]*:" "$WEDI_RC" | cut -d':' -f1 | sort | uniq )
    if [ -z "$FILE" ]; then
      exit 0
    fi
    echo "$FILE"
    exit 0
  else
    echo "CHYBA: Zadany adresar neexistuje" >&2
    exit 1
  fi

elif [ "$1" = "-a" ] || [ "$1" = "-b" ]; then
    if [ "$(uname)" = "Linux" ]; then
      DATEFNC="date"
    else
      DATEFNC="gdate"
    fi
    if echo "$2" | grep -E -q "[0-9]{4}-[0-9]{2}-[0-9]{2}" && "$DATEFNC" -d "$2" >/dev/null
      then
         DATE=$("$DATEFNC" -d "$2" +"%Y%m%d")
         if [ -d "$3" ] && [ $# -eq "3" ]; then
           DIRECTORY=$(realpath "$3")
           if [ "$1" = "-a" ]; then
             FILE=$(grep "$DIRECTORY/[^/]*:" "$WEDI_RC" | cut -d':' -f1,3 | tr -d "-" | awk 'BEGIN { FS = ":" } ; $2>'"$DATE"' {print}' | cut -d':' -f1 | sort | uniq)
           else
             FILE=$(grep "$DIRECTORY/[^/]*:" "$WEDI_RC" | cut -d':' -f1,3 | tr -d "-" | awk 'BEGIN { FS = ":" } ; $2<='"$DATE"' {print}' | cut -d':' -f1 | sort | uniq)
           fi
           if [ -z "$FILE" ]; then
             exit 0
           fi
           echo "$FILE"
           exit 0
         elif [ $# -eq "2" ]; then
           DIRECTORY=$(realpath .)
           if [ "$1" = "-a" ]; then
             FILE=$(grep "$DIRECTORY/[^/]*:" "$WEDI_RC" | cut -d':' -f1,3 | tr -d "-" | awk 'BEGIN { FS = ":" } ; $2>'"$DATE"' {print}' | cut -d':' -f1 | sort | uniq)
           else
             FILE=$(grep "$DIRECTORY/[^/]*:" "$WEDI_RC" | cut -d':' -f1,3 | tr -d "-" | awk 'BEGIN { FS = ":" } ; $2<='"$DATE"' {print}' | cut -d':' -f1 | sort | uniq)
           fi
           if [ -z "$FILE" ]; then
             exit 0
           fi
           echo "$FILE"
           exit 0
         elif [ "$#" -eq 3 ]; then
           echo "CHYBA: Zadany adresar neexistuje" >&2
           exit 1
         else
           echo "CHYBA:Skript byl spusten s nespravnymi parametry." >&2
           exit 1
         fi
    else
      echo "CHYBA:Zadane datum neni validni." >&2
      exit 1
    fi
else
  echo "CHYBA:Skript byl spusten s nepsravnymi parametry."
  exit 1
fi
